AudioInBus: public
AudioInPort: '9876'
AudioOutBus: public
AudioOutPort: '9875'
BargeIn: false
FfmpegCmd: ffmpeg
LocalSPKR: true
LogLevel: e
MicLevelCmd: pactl set-source-volume $(pactl info | grep "Default Source" | cut -d " " -f3) %s
MicLocal: true
MicRemote: false
MicVad: Normal
MinConf: '6.5'
MsgBus: public
MsgBusPort: '4000'
PlayWavCmd: aplay %s  >/dev/null 2>&1
RecordWavCmd: arecord
RemoteSPKR: false
STT: local
STTKey: ''
STTModel: tiny.en
STTService: whisper
STTUseGPU: false
Skills: []
SpkrLevelCmd: amixer -D pulse sset Master %s
TTS: local
TTSKey: ''
TTSService: piper
TTSVoice: en_US-lessac-low.onnx
